version: '2'

services:
      
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: unless-stopped
    volumes:
      - ${CONFIG}/mariadb:/config
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    restart: unless-stopped
    volumes:
      - ${CONFIG}/nextcloud:/config
      - ${BASE}/nextcloud:/data
    ports:
      - 444:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=443
      - traefik.frontend.rule=Host:nextcloud.${DOMAIN}
      - traefik.protocol=https
      
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}:/media:ro
      - /tmp:/transcode
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8484:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:sabnzbd.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    volumes:
      - ${CONFIG}/tautulli:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8181
      - traefik.frontend.rule=Host:tautulli.${DOMAIN}
      
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command: --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 801:80
      - 4431:443
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:monitor.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - traefik.port=8080
