version: '2'
services:
  crashplan:
    container_name: crashplan
    image: jlesage/crashplan-pro
    restart: unless-stopped
    volumes:
      - /storage/docker/crashplan:/config
      - /storage/nextcloud:/nextcloud:ro
      - /storage/mne:/mne:ro
      - /storage/media:/media:ro
      - /storage/downloads/crashplan:/downloads
    ports:
      - "7810:5800"
      - "7910:5900"
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - UMASK=000
      - TZ=${TZ}
      - KEEP_APP_RUNNING=1
      - CRASHPLAN_SRV_MAX_MEM=8192M
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/letsencrypt
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /storage/docker/letsencrypt:/config:rw
    ports:
      - "801:80"
      - "4431:443"
    environment:
      - EMAIL=${EMAIL}
      - URL=${URL}
      - SUBDOMAINS=www,nextcloud
      - ONLY_SUBDOMAINS=false
      - DHLEVEL=4096
      - VALIDATION=http
      - PUID=${PUID}
      - PGID=${PGID}
      - HTTPVAL=true
      - TZ=${TZ}
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: unless-stopped
    volumes:
      - /storage/docker/mariadb:/config:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    restart: unless-stopped
    volumes:
      - /storage/docker/nextcloud:/config:rw
      - /storage/nextcloud:/data:rw
    ports:
      - "444:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    network_mode: host
    volumes:
      - /storage/docker/plex:/config
      - /storage/media:/media:ro
      - /tmp:/transcode
    environment:
      - PLEX_CLAIM=CLAIM-UALQOZQNHA7ZSZY8PQ2A
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    restart: unless-stopped
    volumes:
      - /storage/docker/plexpy:/config
      - /storage/docker/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - /storage/docker/radarr:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - /storage/docker/sabnzbd:/config
      - /storage/downloads:/downloads
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - /storage/docker/sonarr:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
