version: '2'

services:

  crashplan:
    container_name: crashplan
    image: jlesage/crashplan-pro
    restart: unless-stopped
    volumes:
      - ${CONFIG}/crashplan:/config
      - ${BASE}/nextcloud:/nextcloud:ro
      - ${BASE}/mne:/mne:ro
      - ${MEDIA}:/media:ro
      - ${DOWNLOADS}/crashplan:/downloads
      - ${BASE}/backup:/backup:ro
      - ${BASE}/docker:/docker:ro
      - ${BASE}/domains:/domains:ro
      - ${BASE}/isos:/isos:ro
      - ${BASE]/games:/games:ro
    ports:
      - "7810:5800"
      - "7910:5900"
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - UMASK=000
      - TZ=${TZ}
      - KEEP_APP_RUNNING=1
      - CRASHPLAN_SRV_MAX_MEM=8192M
    labels:
      - traefik.enable=true
      - traefik.port=5800
      - traefik.frontend.rule=Host:crashplan.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - com.centurylinklabs.watchtower.enable=true

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: unless-stopped
    volumes:
      - ${CONFIG}/mariadb:/config:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true

  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    restart: unless-stopped
    volumes:
      - ${CONFIG}/nextcloud:/config:rw
      - ${BASE}/nextcloud:/data:rw
    ports:
      - "444:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=443
      - traefik.frontend.rule=Host:nextcloud.${DOMAIN}
      - traefik.protocol=https
      - com.centurylinklabs.watchtower.enable=true

  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    hostname: plex
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}:/media:ro
      - /tmp:/transcode
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - ADVERTISE_IP=${ADVERTISE_IP}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      
  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    restart: unless-stopped
    volumes:
      - ${CONFIG}/plexpy:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8181
      - traefik.frontend.rule=Host:plexpy.${DOMAIN}
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:sabnzbd.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - com.centurylinklabs.watchtower.enable=true
      
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command: --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - "801:80"
      - "4431:443"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:monitor.${DOMAIN}
      - traefik.frontend.auth.basic=${BASIC_AUTH}
      - traefik.port=8080
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    command: --cleanup --label-enable --schedule="0 2 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=true
